# Generated by Django 2.2.10 on 2020-07-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200714_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='end_aate',
            new_name='end_date',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=400)),
                ('respondent', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Question')),
            ],
        ),
    ]
